# Generated by Django 3.1.4 on 2020-12-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebanking', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
